{"abstract":[{"type":"text","text":"GCVCardReader is a framework used for the validation of emirates ID cards using the ICP server and extracting data from the card via the NFC chip. A PDF of the data extracted from the ICP validation is provided"}],"metadata":{"role":"collection","symbolKind":"module","roleHeading":"Framework","modules":[{"name":"GCVCardReader"}],"title":"GCVCardReader","externalID":"GCVCardReader"},"hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"type":"heading","anchor":"Overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This framework provides a solution for scanning of EIDA cards using NFC reading and validation of the same in KYC flows. The minimum iOS supported version is iOS 13.0. Functions are provided validation and extraction of relevant information needed for the ICA API and reading of the data via the phone’s NFC reader’."}]}],"kind":"content"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcvcardreader"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcvcardreader"]}],"topicSections":[{"generated":true,"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/Integration"]},{"title":"Classes","generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GcCardReader"]},{"anchor":"Protocols","identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GcCardReaderProtocol"],"title":"Protocols","generated":true},{"generated":true,"anchor":"Structures","title":"Structures","identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/EIDACardData","doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/EIDAHomeAddress","doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/EIDAICAData"]},{"generated":true,"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCCardReaderError","doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCDataGroupId","doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCNFCConnectFailedError","doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCNFCDisplayMessage"]},{"generated":true,"title":"Extended Modules","identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/UIKit"],"anchor":"Extended-Modules"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader":{"title":"GCVCardReader","identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader","abstract":[{"text":"GCVCardReader is a framework used for the validation of emirates ID cards using the ICP server and extracting data from the card via the NFC chip. A PDF of the data extracted from the ICP validation is provided","type":"text"}],"kind":"symbol","url":"\/documentation\/gcvcardreader","role":"collection","type":"topic"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GcCardReaderProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GcCardReaderProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GcCardReaderProtocol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GcCardReaderProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol which has to be implemented so that the requests can go through the app"}],"url":"\/documentation\/gcvcardreader\/gccardreaderprotocol","kind":"symbol","title":"GcCardReaderProtocol"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GCVCardReaderVersionString":{"role":"symbol","type":"topic","abstract":[{"text":"Project version string for GCVCardReader.","type":"text"}],"identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCVCardReaderVersionString","url":"\/documentation\/gcvcardreader\/gcvcardreaderversionstring","kind":"symbol","fragments":[{"kind":"identifier","text":"GCVCardReaderVersionString"}],"title":"GCVCardReaderVersionString"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/EIDAICAData":{"title":"EIDAICAData","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"EIDAICAData","kind":"identifier"}],"type":"topic","url":"\/documentation\/gcvcardreader\/eidaicadata","abstract":[{"type":"text","text":"Model to return nProbe data"}],"navigatorTitle":[{"text":"EIDAICAData","kind":"identifier"}],"identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/EIDAICAData"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GCNFCConnectFailedError":{"type":"topic","role":"symbol","url":"\/documentation\/gcvcardreader\/gcnfcconnectfailederror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GCNFCConnectFailedError","kind":"identifier"}],"kind":"symbol","title":"GCNFCConnectFailedError","identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCNFCConnectFailedError","abstract":[{"text":"NFC Card connection errors.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GCNFCConnectFailedError"}]},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GCCardReaderError":{"url":"\/documentation\/gcvcardreader\/gccardreadererror","navigatorTitle":[{"kind":"identifier","text":"GCCardReaderError"}],"identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCCardReaderError","abstract":[{"text":"GCCardReaderError","type":"text"}],"title":"GCCardReaderError","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCCardReaderError"}],"kind":"symbol"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/UIKit":{"title":"UIKit","kind":"symbol","identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/UIKit","url":"\/documentation\/gcvcardreader\/uikit","type":"topic","role":"collection","abstract":[]},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/EIDACardData":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"EIDACardData","kind":"identifier"}],"title":"EIDACardData","url":"\/documentation\/gcvcardreader\/eidacarddata","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EIDACardData"}],"identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/EIDACardData","abstract":[{"type":"text","text":"EIDA Card Data"}]},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/Integration":{"title":"Integration steps","type":"topic","url":"\/documentation\/gcvcardreader\/integration","abstract":[{"type":"text","text":"This article provides the list of steps that need to be followed to integrate the GCVCardReader framework into an app."}],"kind":"article","role":"article","identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/Integration"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GCVCardReaderVersionNumber":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCVCardReaderVersionNumber","url":"\/documentation\/gcvcardreader\/gcvcardreaderversionnumber","title":"GCVCardReaderVersionNumber","abstract":[{"type":"text","text":"Project version number for GCVCardReader."}],"fragments":[{"text":"GCVCardReaderVersionNumber","kind":"identifier"}],"role":"symbol"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GcCardReader":{"title":"GcCardReader","type":"topic","url":"\/documentation\/gcvcardreader\/gccardreader","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GcCardReader"}],"abstract":[{"type":"text","text":"Defines public class for the framework. Use the shared instance of this to use all the public methods"}],"identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GcCardReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcCardReader"}]},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GCNFCDisplayMessage":{"abstract":[{"type":"text","text":"Model to define your messages based on NFC Reader actions."}],"title":"GCNFCDisplayMessage","kind":"symbol","url":"\/documentation\/gcvcardreader\/gcnfcdisplaymessage","identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCNFCDisplayMessage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GCNFCDisplayMessage"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GCNFCDisplayMessage"}],"type":"topic"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/EIDAHomeAddress":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"EIDAHomeAddress","kind":"identifier"}],"abstract":[{"text":"EIDA Card Home Address","type":"text"}],"identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/EIDAHomeAddress","kind":"symbol","url":"\/documentation\/gcvcardreader\/eidahomeaddress","type":"topic","navigatorTitle":[{"text":"EIDAHomeAddress","kind":"identifier"}],"title":"EIDAHomeAddress"},"doc://com.gamechangesns.GCVCardReader/documentation/GCVCardReader/GCDataGroupId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCDataGroupId","kind":"identifier"}],"url":"\/documentation\/gcvcardreader\/gcdatagroupid","navigatorTitle":[{"text":"GCDataGroupId","kind":"identifier"}],"type":"topic","title":"GCDataGroupId","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCDataGroupId","abstract":[{"type":"text","text":"Data Group ID"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/Integration"],"generated":true,"title":"Articles","anchor":"Articles"},{"anchor":"Variables","identifiers":["doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCVCardReaderVersionNumber","doc:\/\/com.gamechangesns.GCVCardReader\/documentation\/GCVCardReader\/GCVCardReaderVersionString"],"title":"Variables","generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}